# Generated by Django 4.0.6 on 2024-01-29 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]

